version: '3'
services:
  drupal:
    image: drupal
    ports:
      - "81:80"
    volumes:
      # - ./drupal:/drupal
        - ./drupal:/opt/drupal
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    depends_on:
      - db
  db:
    image: mysql
    #volumes:
    #  - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
#volumes:
  #db_data:
  #drupal_modules:
  #drupal_profiles:
  #drupal_themes:
  #drupal_sites:

